# Generated by Django 4.1.7 on 2023-03-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="city",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
