# Generated by Django 4.1.7 on 2023-03-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0002_alter_tutor_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="email",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
