# Generated by Django 4.2 on 2023-04-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0003_alter_tutor_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abrigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, null=True, unique=True)),
                ("phone", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, null=True)),
                ("age", models.CharField(blank=True, max_length=15)),
                ("size", models.CharField(blank=True, max_length=15)),
                ("caracteristic", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
