# Generated by Django 4.2 on 2023-04-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0005_abrigo_state_pet_abrigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet", old_name="abrigo", new_name="abrigo_id",
        ),
        migrations.AlterField(
            model_name="abrigo", name="phone", field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="pet",
            name="caracteristic",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
