# Generated by Django 4.2 on 2023-04-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0006_rename_abrigo_pet_abrigo_id_alter_abrigo_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet", name="adopted", field=models.BooleanField(default=False),
        ),
    ]
