# Generated by Django 4.2 on 2023-04-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0007_pet_adopted"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="image",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
    ]
