# Generated by Django 4.1.7 on 2023-02-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthYear', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('cnh', models.CharField(max_length=9)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('X', 'Not informed')], default='X', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('tractorYear', models.CharField(max_length=4)),
                ('manufacter', models.CharField(max_length=30)),
                ('lastReview', models.DateField(null=True)),
                ('lastLocation', models.CharField(max_length=100)),
                ('lastFuelDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TractorRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='minasul.driver')),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='minasul.tractor')),
            ],
        ),
    ]
