# Generated by Django 4.1.7 on 2023-02-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minasul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='identification',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
